# Site settings
author: Margarita Khodzka
title: Margarita Khodzka learns
header-img: img/home-bg.png
email: mkhodzka@gmail.com
copyright_name: Margarita Khodzka
description: > # this means to ignore newlines until "baseurl:"
  Blog on Learn
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MargaritaKhodzka

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
